### ISSUE TITLE
Roadmap v3

### ISSUE THREAD

**Issue by caouecs** [caouecs/Laravel-lang#531]
Hello,
the aim of this project is the translation of Laravel files, all Laravel versions, and just translations.

For the version 3 :

 * [x] new name for Composer : caouecs/laravel-lang
 * [x] translated files in src directory
 * [x] documentation

**Comment by arcanedev-maroc** [comment]
You forgot about moving all the translations into the new `src` folder (Major change).

**Comment by caouecs** [comment]
No, because for me, this project is just for files of translation, readme and todo list. The script for todo list will be on another project. 

So you Will be able to use this project for your own projects, without dependencies or constraints.

**Comment by arcanedev-maroc** [comment]
Even if this package contains only translation files but it needs to follow some conventions.

The idea behind the `src` folder is very obvious and explains itself => This is the main folder and it contains all translations.

As a dependency that i use for my package, it's an assurance that is not gonna fail on me like the case where you added the `script` folder.

You can keep the `script` folder with this solution and you can create even more folders and stuff without breaking other packages, because everyone gonna use directly the `src` and it's 100% gonna have only the locales and their translations (and of course, without files like `README.md`, `TODO.md` and stuff).

For more details: #526 

For the sake of maintainability, this is the best solution i can tell. If you have a good reason or solution for everyone, please share with us.

**NOTE :** The changes mentioned above aren't major changes, so the version will still **v2.x.x**.

**Comment by caouecs** [comment]
done ;)

**Comment by arcanedev-maroc** [comment]
Is there any progress ?

**Comment by caouecs** [comment]
Hello,
sorry but I'm on vacation ;)

**Comment by caouecs** [comment]
changelog updated

**Comment by arcanedev-maroc** [comment]
How about adding the `CHANGELOG.md`, `LICENSE.md` and `CONTRIBUTING.md` files and keep the `README.md` file skinny and clean ?

Like this repo: https://github.com/thephpleague/skeleton

**Comment by caouecs** [comment]
You can

**Comment by arcanedev-maroc** [comment]
Hi @caouecs, great work :+1: 

About the *version for Laravel 5.2 with uppercase on variables*, nice feature to have in Laravel, i didn't know that :smile:.

But, i prefer to stick with the default `en` translations (Like this [validation.php file](https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php) or [this one](https://github.com/caouecs/Laravel-lang/blob/v3/script/en/validation.php)) offered by Laravel and also it's compatible with Laravel 5.1.

**Comment by caouecs** [comment]
I do two versions, one for Laravel 5.1 and one for Laravel 5.2 and uppercase ? ;)

**Comment by arcanedev-maroc** [comment]
I mean that the `caouecs/laravel-lang:v3` is going to be compatible with Laravel `5.1` & `5.2` if you keep the lowercase `:attribute` (backward compatibility).

**Comment by caouecs** [comment]
Maybe, but I think a v3.1 can just be for Laravel 5.2 ;)

**Comment by arcanedev-maroc** [comment]
As you like. But it you group them in one branch, you're going to avoid extra work to maintain them.

**Comment by caouecs** [comment]
Laravel 5.1 is LTS version... so for v3, I'm ok to delete the uppercase variable

**Comment by caouecs** [comment]
I added in README.md a list of projects based on this project

**Comment by caouecs** [comment]
@arcanedev-maroc I think now the v3 is ready

**Comment by arcanedev-maroc** [comment]
Hi @caouecs,

The `:Attribute` with capital **A** still in some languages like `ca`, `cs`, `da` ...

After that, i think the v3 is ready to be released :+1:

**Comment by caouecs** [comment]
done

**Comment by caouecs** [comment]
If all is good, this evening ( French hour ), I will merge v3 in master
